### ISSUE TITLE
Remove @asyncio.coroutine + 3.4 Support

### ISSUE THREAD

**Issue by cooperlees** [mosquito/aiohttp-xmlrpc#26]
What are the thoughts of dropping 3.4 support and mainly `@asyncio.coroutine` decorator now we're in 2020 and many versions of Python ahead. This would be replaced with `async def` coroutine creation.

3.4 is not the default anymore on most popular Linux distros too,

**Comment by graingert** [comment]
this is also required for `async/with` support

**Comment by mosquito** [comment]
@graingert do you want to make PR?

**Comment by mosquito** [comment]
So Python 3.4 support might be dropped for new versions.

**Comment by cooperlees** [comment]
I +1 on dropping 3.4 support. It’s not support by Core Devs anymore. 3.4 users can pin to One of the the last 3.4 supporting versions.
