### ISSUE TITLE
Custom User Agent

### ISSUE THREAD

**Issue by Diaoul** [mosquito/aiohttp-xmlrpc#8]
Although it's nice that the ServerProxy comes with its predefined UserAgent, I'd need to use my own. Could you please make it so it is an argument to `__init__`?

**Comment by mosquito** [comment]
Are you sure that you want to pass it into `__init__`? I thought if someone will want to change it, the simple solution it is the inheriting.

```python
class MyServerProxy(ServerProxy):
    USER_AGENT="My User Agent"
```

**Comment by Diaoul** [comment]
Both are ok, I mainly wanted to avoid subclassing just for this. Even if I provide my own ClientSession with its own useragent it would be overridden.

**Comment by Diaoul** [comment]
Actually I could use the kwargs to pass arguments from the ServerProxy to the ClientSession with headers but that would be overridden as well.

So what I would expect from the ServerProxy (let me know if you agree):
* If I have a custom user agent in my custom client it doesn't override it
* If I supply my custom user agent through kwargs it doesn't override it
* Otherwise override it

This has the advantage of not needing any extra arguments.

**Comment by mosquito** [comment]
I already added the `headers` argument for the `ServerProxy` in `0.6.0`. Please reopen this issue when that's not enough for you.
